workspace:
  base: /go
  path: src/github.com/uswitch/brigade

pipeline:
  build:
    when:
      event: push
    image: golang:1.9
    environment:
      - GOPATH=/go
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o brigade-api/rootfs/brigade-api brigade-api/cmd/brigade-api/main.go

  docker:
    when:
      event: push
    image: plugins/docker
    dockerfile: brigade-api/Dockerfile
    repo: registry.usw.co/uswitch/ldn/brigade-api
    tag:
      - latest
      - "${DRONE_COMMIT_SHA}"
